image: docker:20.10.16

services:
  - docker:20.10.16-dind
  - name: postgres:17
    alias: db
  - name: redis:latest
    alias: redis

variables:
  DOCKER_TLS_CERTDIR: ""
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "app_test"
  REDIS_URL: "redis://redis:6379/0"
  RAILS_ENV: "test"

stages:
  - test

before_script:
  - apk add --no-cache docker-compose
  - cp backend/config/database.yml.ci backend/config/database.yml

test:
  stage: test
  script:
    - docker-compose -f docker-compose.ci.yml up -d db redis
    - docker-compose -f docker-compose.ci.yml up -d backend
    - docker-compose -f docker-compose.ci.yml exec -T backend bash -c "bundle exec rails db:create db:migrate && bundle exec rspec"


