services:
  db:
    image: postgres:14
    container_name: chatbot_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_development
    networks:
      - chatbot_builder_network

  web:
    build: .
    container_name: chatbot_builder
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "postgres://postgres:password@db:5432/chatbot_development"
    networks:
      - chatbot_builder_network
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - ~/.bash_history:/root/.bash_history
      - node_modules:/rails/node_modules
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  frontend:
    build: .
    container_name: chatbot_frontend
    image: chatbot_builder
    restart: on-failure
    ports:
      - "3035:3035"
    env_file: .env
    networks:
      - chatbot_builder_network
    environment:
      NODE_ENV: development
    volumes:
      - .:/rails
      - node_modules:/rails/node_modules
    command: ["sh", "-c", "yarn build && yarn watch"]

volumes:
  db_data:
  node_modules:
  bundle_cache:

networks:
  chatbot_builder_network:
    name: chatbot_builder_network